kibot:
  version: 1

filters:
  - name: only_jlc_parts
    comment: Only parts with JLC (LCSC) code
    type: generic
    include_only:
      - column: 'LCSC'
        regex: '^C\d+'

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  - name: print_sch
    comment: Print schematic (PDF)
    type: pdf_sch_print
    dir: .
    options:
      output: schematic.pdf

  - name: print_pcb_top
    comment: Print F.Cu + F.Silkscreen
    type: pdf_pcb_print
    dir: .
    options:
      output_name: pcb_top.pdf
    layers:
      - F.Cu
      - F.Silkscreen

  - name: print_pcb_bottom
    comment: Print B.Cu + B.Silkscreen
    type: pdf_pcb_print
    dir: .
    options:
      output_name: pcb_bottom.pdf
    layers:
      - B.Cu
      - B.Silkscreen

  - name: gerber_files
    comment: Gerber files compatible with JLCPCB
    type: gerber
    dir: gerbers
    options:
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
    layers:
      - F.Cu
      - B.Cu
      - F.Paste
      - B.Paste
      - F.Silkscreen
      - B.Silkscreen
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: drill_files
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: gerbers
    options:
      pth_and_npth_single_file: false
      pth_id: PTH
      npth_id: NPTH
      metric_units: true
      route_mode_for_oval_holes: false
      map:
        output: "%f-%i_drl.%x"
        type: gerber

  - name: pick_and_place
    comment: Pick and place file, JLCPCB style
    type: position
    dir: ./
    options:
      output: pp.%x
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: bill_of_materials
    comment: BoM for JLCPCB
    type: bom
    dir: ./
    options:
      output: bom.%x
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC'
          name: 'LCSC Part Number'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: fabrication_files
    comment: ZIP fabrication file for JLCPCB
    type: compress
    dir: ./
    options:
      output: gerbers.%x
      files:
        - from_output: gerber_files
          dest: /
        - from_output: drill_files
          dest: /
